Lubimyi2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from app.views import *

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', index, name='index'),
    url(r'^contacts/$', contacts, name='contacts'),
    url(r'^adders/$', adders, name='adders'),
    url(r'^adder/(?P<id>\d+)$$', adders_single, name='adders_single'),
    url(r'^tv_project/(?P<id>\d+)$', tv_project_single, name='tv_project_single'),
    url(r'^table/$', table, name='table'),
    url(r'^projects/$', projects, name='projects'),
    url(r'^about_us/$', about_us, name='about_us'),
    url(r'^portfolio/$', portfolio, name='portfolio'),
    url(r'^add/$', add, name='add'),
    url(r'page/(\d+)/$', portfolio, name='portfolio_page'),
    url(r'^copy_items', copy_items, name='copy_items'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_models/models.py
# coding=utf-8
from __future__ import unicode_literals
import csv
from Lubimyi2.media_path import *
from sorl.thumbnail import ImageField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
from Lubimyi2.settings import MEDIA_ROOT
from app_models.helper import transform

pathFile = 'posts/file'
pathImg = 'images'


class Banner(models.Model):
    class Meta:
        db_table = 'banner'
        verbose_name = 'Баннер'
        verbose_name_plural = 'Баннеры'

    title = models.CharField(max_length=255, verbose_name='Наименование', blank=True, null=True)
    short_description = models.CharField(max_length=150, verbose_name='Краткое описание', blank=True, null=True)
    date = models.CharField(max_length=255, verbose_name='дата', default='', blank=True)
    # description = RichTextField(verbose_name='Описание')
    image = models.ImageField(upload_to='', verbose_name='Изображение')

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title


class Contacts(models.Model):
    class Meta:
        db_table = 'contacts'
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'

    mail = models.EmailField(verbose_name='E-mail')
    name = models.CharField(max_length=255, verbose_name='Имя')
    number = PhoneNumberField(verbose_name='НОмер телефона')
    comment = RichTextUploadingField()

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.name


class Adders(models.Model):
    class Meta:
        db_table = 'adders'
        verbose_name = 'Рекламодателям'
        verbose_name_plural = 'Рекламодателям'

    title = models.CharField(max_length=255, verbose_name='Название')
    description = RichTextUploadingField(verbose_name='Описание')
    image = ImageField(upload_to=transform(pathImg), verbose_name='Изображение')

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title


class Videos(models.Model):
    class Meta:
        db_table = 'videos'
        verbose_name = 'видео'
        verbose_name_plural = 'видео'

    title = models.CharField(max_length=255, verbose_name='Название')
    # link = models.URLField(default='')
    url = models.CharField(max_length=100, verbose_name='ссылка', blank=True,
                           help_text='не вся ссылка, только ключ видео')
    image = ImageField(upload_to=transform(pathImg), verbose_name='Изображение')

    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title


class Post(models.Model):
    class Meta:
        db_table = 'table'
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'

    # date = models.CharField(verbose_name='дата', default='', max_length=20)
    date_char = models.DateField(verbose_name='Дата')
    title = models.CharField(max_length=250, verbose_name='Наименование')
    type = models.CharField(max_length=250, verbose_name='Жанр')
    time_begin = models.TimeField(verbose_name='Время начала', blank=True, null=True)
    # during_time = models.DurationField(verbose_name='длительность', null=True)
    time_end = models.TimeField(verbose_name='Время завершения', null=True)

    # timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    # updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title

        # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        #     time_end = self.during_time,self.time_begin
        #     print time_end
        #     self.time_end = time_end
        #     super(Post, self).save()


class Tv_projects(models.Model):
    class Meta:
        db_table = 'tv_projects'
        verbose_name = 'телепроект'
        verbose_name_plural = 'телепроекты'

    title = models.CharField(max_length=255, verbose_name='название')
    short_description = models.CharField(max_length=1000, verbose_name='Краткое описание')
    description = RichTextUploadingField(verbose_name='Описание')
    image = models.ImageField(upload_to=transform(pathImg), verbose_name='Изображение')

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title


class File(models.Model):
    class Meta:
        db_table = 'file'
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    title = models.TextField(max_length=100)
    file = models.FileField(upload_to=transform(pathFile))

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.title


@receiver(post_save, sender=File, dispatch_uid='File_Reader')
def save_table(sender, instance, *args, **kwargs):
    # File.objects.all().delete()
    # Post.objects.all().delete()

    with open(MEDIA_ROOT + '/' + str(instance.file)) as f:
        reader = csv.reader(f, delimiter=str(u'\t').encode('utf-8'), skipinitialspace=True)
        for cols in reader:
            old_date = cols[0].split('.')
            table = Post()
            new_date = old_date[2] + '-' + old_date[1] + '-' + old_date[0]
            table.date_char = new_date
            table.time_begin = cols[1]
            table.time_end = cols[2]
            # table.time_end = cols[3]
            table.title = str(cols[3]).decode("cp1251")
            if table.type:
                table.type = str(cols[4]).decode("cp1251")
            else:
                table.type = ''
            table.save()

app_models/forms.py
# coding=utf-8
from __future__ import unicode_literals

from django import forms
from django.db import models
from django.forms import ModelForm

from app_models.models import Contacts


class ContactForm(ModelForm):
    class Meta:
        model = Contacts
        exclude = ()

    name = forms.CharField(required=False)

templates/app/about_us.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}О НАС{% endblock %}
{% block content %}
    <!--banner-->
<div class="container-fluid media_sign">
    <div class="container media_sign">
        <div class="about-left">
            <img src="{% static 'images/tv.png' %}" alt="">
        </div>
        <div class="about-right">
            <h1>MEDIASIGN <br/> GROUP</h1>
            <p>РА «MEDIASIGN GROUP» – рекламное агентство полного цикла,
                существующее на медиа-рынке Кыргызстана с 2007 года.
                Команда профессионалов «MEDIASIGN GROUP», опираясь на многолетний опытработы и богатую практику,
                гарантирует качественное выполнение поставленных задач в сжатые сроки.</p>
        </div>
    </div>
</div>
<!--banner end-->

<!--body-->


<!--body end-->
<div class="container-fluid services" >
    <div class="services">
        <h1>Услуги и продукты РА <br/>
            «MEDIASIGN GROUP»</h1>
    </div>
    <div class="container services">

        <div class="service-left">
            <p>Телевизионные проекты: «Любимый Город», «Строительный вопрос» , «AUTO DRIVE», «Здоровая страна»,
                «Культурные ценности», «Для тебя», «Про спорт», выходящие в телевизионный эфир в prime-time каждую
                неделю на четырех республиканских и четырех локальных телеканалах. Единственные проекты на телевидение,
                превосходящие телевизионный контент производимый в Кыргызстане по масштабности трансляции и качеству
                производства.
                Телепроекты которые смотрят миллионы Кыргызстанцев по всей стране.
                <br/>
                <br/>
                Production studio: графические и постановочные рекламные ролики, PR-сюжеты, документальные и
                художественные
                фильмы.
                Собственная производственная база и наличие собственного оборудования позволяет сокращать издержки на
                создание
                видео и аудио контента, что в свою очередь существенно снижает стоимость выполнения заказа для клиента.
                <br/>
                <br/>
                Телевизионный канал «Любимый»TV HD: информационно- развлекательный канал во всех сетях г. Бишкек и
                Кыргызской
                Республики:
                Республиканское Цифровое вещание Санарип (Sanarip), АК-НЕТ, Smart TV, Zor TV, City Net, Dolon TV, Mega
                Line,
                i
                TV,
                On-line TV, аi TV, Asia Net TV, Totel TV, Saima TV, Telecom TV, Namba.kg, TS.KG, также в on-line эфире
                на
                сайте
                www.lctv.kg
                <br/>
                <br/>
                В совокупности количество телезрителей указанных сетей может достигать более 4 900 000 человек.</p>
        </div>
        <div class="service-right">
            <p>BTL: организация и проведение BTL и Event – мероприятий, адресная разноска РИМ, прямые презентации и
                продажи
                товара.
                <br/>
                <br/>
                Видео витрина: полный комплекс услуг по созданию видео витрин: мониторинг месторасположения витрины и
                условий
                монтажа оборудования, создание видеоряда, изготовление проекционной витрины, установка и обслуживание.
                <br/>
                <br/>
                Mediabuying: весь спектр услуг медиа – планирования, от крупных телеканалов и радиостанций до локальных
                региональных ТВ и радио, а также распространение аудио-рекламы посредством радио-рубок на рынках и
                торговых
                центрах.
                <br/>
                <br/>
                Анализ рынка, целевой аудитории и маркетинговой ситуации: коммуникационная стратегия, marketingindex,
                специальные исследования
                <br/>
                <br/>
                Определение приоритетных категорий СМИ: использованием баз данных TV Index, Web Index, Radio Index,
                National
                Readership Survey
                <br/>
                <br/>
                Построение стратегии и тактики, планирование этапов рекламной кампании
                <br/>
                <br/>
                Рекомендации по построению первичной и последующей маркетинговой активности.</p>
        </div>
    </div>
</div>
<div class="container-fluid gradient">
    <div class="container gradient">
        <div class="document">
            <img src="{% static 'images/document.png' %}" alt="">
        </div>
        <div class="document-content">
            Телеканал «Любимый TV» HD <br>
            является эксклюзивным партнером <br>
            ООО «Централ Партнёршип Сейлз Хаус».
        </div>
    </div>
    <!--<img src="images/gradient.png" alt="">-->
</div>
{% endblock %}

templates/app/adders.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks thumbnail %}
{% block title %}РЕКЛАМОДАТЕЛЯМ{% endblock %}
{% block content %}
    <!--body-->
    <div class="container develop" style="margin-bottom: 50px">
        <div class="develop">
            <h1>РЕКЛАМА НА НАШЕМ КАНАЛЕ</h1>
            <div class="developing">
                {% for add in adders %}
                    {% if forloop.counter == 2 %}
                        <a href="{% url 'adders_single' id=add.id %}">
                            <div class="develop-content">
                                {% thumbnail add.image "226x226" crop="center" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% endthumbnail %}

                                <div class="develop-text">
                                    <div class="text">
                                        <p style="padding-top: 76px">{{ add.title|safe }}</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% else %}
                        {#                    {% elif forloop.counter <= 8 %}#}
                        <a href="{% url 'adders_single' id=add.id %}">
                            <div class="develop-content">
                                <img src="{{ add.image.url }}" alt="">
                                <div class="develop-text">
                                    <div class="text">
                                        <p>{{ add.title|safe }}</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {#    <div class="container dev">#}
    {#        {% for add in adders %}#}
    {#            {% if forloop.counter >= 9 %}#}
    {#                <a href="{% url 'adders_single' id=add.id %}">#}
    {#                    <div class="develop-content ">#}
    {#                        <img src="{{ add.image.url }}" alt="">#}
    {#                        <div class="develop-text">#}
    {#                            <div class="text">#}
    {#                                <!--<div class="shadow-text">-->#}
    {#                                <p>{{ add.title|safe }}</p>#}
    {#                                <!--</div>-->#}
    {#                            </div>#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </a>#}
    {#            {% endif %}#}
    {#        {% endfor %}#}


    </div>
    <!--body end-->
{% endblock %}

templates/app/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}КОНТАКТЫ{% endblock %}

{% block content %}
    <div class="container content" style="margin-bottom: 50px">
        <h2>СВЯЖИТЕСЬ С НАМИ</h2>
        <form id="contact" action="{% url 'contacts' %}" method="POST" name="">
            <div class="row">
                <div class="alert" style="display: none" id="alert">

                </div>
                <div class="col-md-6 form-left col-sm-6">
                    {% render_field form.name placeholder="Имя" required='required' class="name" %}
                    {#                    <input type="text" class="name" placeholder="Имя">#}
                    {% render_field form.mail placeholder="Ваш E-mail" required='required' class="e-mail" %}

                    {% render_field form.number placeholder="Телефон" required='required' class="number" %}
                    {#                    <input type="text" class="number" placeholder="Телефон">#}
                </div>
                <div class="col-md-6 form-right col-sm-6">
                    {% render_field form.comment placeholder="Опишите ваш запрос..." class="comments" %}
                    {#                <textarea name="" id="" cols="30" rows="10" class="comments"#}
                    {#                          placeholder="Опишите ваш запрос..."></textarea>#}
                    {% csrf_token %}
                </div>
            </div>

            <button>ОТПРАВИТЬ</button>

        </form>
    </div>

{% endblock %}

{% block custom_scripts %}
    <script>
        $(document).ready(function () {
            $('#contact').on('submit', function (e) {
                e.preventDefault();
                var data = $(this).serialize();
                var that = this;
                var alert = $('#alert');
                $(alert).removeClass('alert-danger').removeClass('alert-success');
                $.ajax({
                    url: $(that).attr('action'),
                    method: 'POST',
                    dataType: 'JSON',
                    data: data,
                    success: function (response) {
                        $(alert).fadeIn('fast');
                        if (response.success) {
                            $(alert).addClass('alert-success');
                            $(alert).html(response.message);
                        } else {
                            $(alert).addClass('alert-danger');
                            $(alert).html(response.message);
                        }
                        $('#id_name').val('');
                        $('#id_mail').val('');
                        $('#id_number').val('');
                        $('#id_comment').val('');
                    },
                    error: function () {
                        $(alert).fadeIn('fast');
                        $(alert).addClass('alert-danger');
                        $(alert).html('Произошла неизвестная ошибка...');
                        $(that).clean();
                        $('#id_name').val('');
                        $('#id_mail').val('');
                        $('#id_number').val('');
                        $('#id_comment').val('');
                    }
                });
            })
        });
    </script>
    <script src="http://cdn.dashjs.org/latest/dash.all.min.js"></script>
{% endblock %}

templates/app/portfolio.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks thumbnail %}
{% load template_helpers %}
{% block title %}ПОРТФОЛИО{% endblock %}
{% block content %}
    <div class="container videos" style="max-width: 960px; padding: 0;">

        {% for vd in videos %}
            {#            {% if forloop.counter <=2 in page %}{% endif %}#}

            <div class="video-content">
                <a href="#" data-toggle="modal" data-target="#myModal" data-link="{{ vd.url }}"
                   class="modal-trigger">
                    {% thumbnail vd.image "300x300" crop="center" as im %}
                <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}

                <div class="video-text">
                    <div class="text">
                        <div class="video-title">
                            <p>{{ vd.title|safe }}</p>
                        </div>
                    </div>
                </div>
            </a>
            </div>


            <!-- Modal -->


        {% endfor %}

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document" id="video-modal">
            </div>
        </div>


    </div>
    {#  Pagination   #}
    <div class="container" style="margin: auto; text-align: center">
        {% with videos.paginator.num_pages as num_pages %}
            {% with videos.number as current_page_number %}
                {% set 0 as dots_counter %}
                {% set 0 as dot_number %}
                {% if videos.paginator.num_pages > 1 %}
                    <ul class="pagination" id="pagination">
                        {% if videos.has_previous %}
                            <li><a href="/page/{{ videos.previous_page_number }}" id="prev-page"><<</a></li>
                        {% endif %}
                        {% for page in videos.paginator.page_range %}
                            {% show_link page num_pages current_page_number as is_showing_link %}
                            {% if is_showing_link %}
                                {% set 0 as dots_counter %}
                                {% if page == videos.number %}
                                    <li class="active">
                                        <a href="/page/{{ page }}">{{ page }}</a>
                                    </li>
                                {% elif page != videos.number %}
                                    <li>
                                        <a href="/page/{{ page }}">{{ page }}</a>
                                    </li>
                                {% endif %}

                            {% else %}
                                {% if dots_counter == 0 %}
                                    {% set 1 as dots_counter %}
                                    <li><a href="#" class="disabled">...</a></li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if videos.has_next %}
                            <li><a href="/page/{{ videos.next_page_number }}" id="next_page">>></a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            {% endwith %}
        {% endwith %}
    </div>

    <!--Block "Пагинация" End"-->

{% endblock %}
{% block custom_scripts %}
    <script type="text/javascript">
        $('.popup .close_window, .overlay').click(function () {
            $('.popup, .overlay').css({'opacity': 0, 'visibility': 'hidden'});
        });
        $('a.open_window').click(function (e) {
            $('.popup, .overlay').css({'opacity': 1, 'visibility': 'visible'});
            e.preventDefault();
        });
    </script>
    <script>
        $('.thumbnail').click(function () {
            $('.modal-body').empty();
            var title = $(this).parent('a').attr("title");
            $('.modal-title').html(title);
            $($(this).parents('div').html()).appendTo('.modal-body');
            $('#myModal').modal({show: true});
        });

        /* blur on modal open, unblur on close */
        $('#myModal').on('show.bs.modal', function () {
            $('.col-6,.row .thumbnail').addClass('blur');
        })

        $('#myModal').on('hide.bs.modal', function () {
            $('.col-6,.row .thumbnail').removeClass('blur');
        })
    </script>

    <script>
        $(document).ready(function () {
            var triggers = $('.modal-trigger');

            $(triggers).each(function (i, obj) {
                $(obj).on('click', function (e) {
                    e.preventDefault();
                    $('#video-modal').html('<iframe width="950" height="534" src="https://www.youtube.com/embed/' + $(this).attr('data-link') + '?rel=0" frameborder="0" allowfullscreen id="video-source"></iframe>');
                })
            });
        });
    </script>
{% endblock %}

templates/app/projects.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks thumbnail %}
{% block title %}ПРОЕКТЫ{% endblock %}
{% block content %}
    <!--banner-->
    <div class="container-fluid projects">
        <div class="container all_projects">
            <h1> НАШИ ТЕЛЕПРОЕКТЫ В ФОРМАТЕ ГОРОДА И РЕСПУБЛИКИ </h1>
            <div class="tv-projects">
                {% for tv in tv_project %}
                    {% if forloop.counter <= 4 %}
                        <a href="{% url 'tv_project_single' id=tv.id %}">
                            <div class="project-single">
                                <div class="project_image">
                                    {% thumbnail tv.image "227x365" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                    <div class="project-title">
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-top">
                                        <h5>{{ tv.title|safe }}</h5>
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-bottom">
                                    </div>
                                </div>
                                <div class="project-info" style="color:#fbfbfb">
                                    <p>{{ tv.short_description|safe }}</p>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="container-fluid prsecond">
        <div class="container prsecond all_projects">
            {#            <h1 style="color: #282828; text-align: center"></h1>#}
            <div class="tv-projects">
                {% for tv in tv_project %}
                    {% if forloop.counter > 4 and forloop.counter <= 7 %}
                        <a href="{% url 'tv_project_single' id=tv.id %}">
                            <div class="project-single">
                                <div class="project_image">
                                    {% thumbnail tv.image "227x365" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                    <div class="project-title">
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-top">
                                        <h5>{{ tv.title|safe }}</h5>
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-bottom">
                                    </div>
                                </div>
                                <div class="project-info land" style="color:#fbfbfb">
                                    <p>{{ tv.short_description|safe }}</p>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% for tv in tv_project %}
        {% if forloop.counter > 7 and forloop.counter <= 11 %}
            <div class="container-fluid projects">
                <div class="container all_projects">
                    {#            <h1> НАШИ ТЕЛЕПРОЕКТЫ В ФОРМАТЕ ГОРОДА И РЕСПУБЛИКИ </h1>#}
                    <div class="tv-projects">

                        <a href="{% url 'tv_project_single' id=tv.id %}">
                            <div class="project-single">
                                <div class="project_image">
                                     {% thumbnail tv.image "227x365" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                    <div class="project-title">
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-top">
                                        <h5>{{ tv.title|safe }}</h5>
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-bottom">
                                    </div>
                                </div>
                                <div class="project-info" style="color:#fbfbfb">
                                    <p>{{ tv.short_description|safe }}</p>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% for tv in tv_project %}
        {% if forloop.counter > 11 and forloop.counter <= 14 %}
            <div class="container-fluid prsecond">
                <div class="container prsecond all_projects">
                    {#            <h1 style="color: #282828; text-align: center"></h1>#}
                    <div class="tv-projects">

                        <a href="{% url 'tv_project_single' id=tv.id %}">
                            <div class="project-single">
                                <div class="project_image">
                                    {% thumbnail tv.image "227x365" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                    <div class="project-title">
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-top">
                                        <h5>{{ tv.title|safe }}</h5>
                                        <img src="{% static 'images/line.png' %}" alt="" class="line-bottom">
                                    </div>
                                </div>
                                <div class="project-info land" style="color:#fbfbfb">
                                    <p>{{ tv.short_description|safe }}</p>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}


    <!--banner end-->


    <!--body-->

    <!--body end-->

{% endblock %}